# Tensor Basics

In [8]:
import torch

# empty is uninitialized data
x = torch.empty(2, 3)
print(x)

# random tensor
y = torch.rand(2,3)
print(y)

# spedify datatype
z = torch.ones(2,3, dtype=torch.float16)
print(z)
print(z.size())

# constructing a tensor from data
# e.g: python list
k = torch.tensor([2.5, 0.1])
print(k)

tensor([[2.1893e-17, 3.0798e-41, 9.2892e-19],
        [3.0798e-41, 8.9683e-44, 0.0000e+00]])
tensor([[0.7400, 0.3028, 0.1924],
        [0.5323, 0.9281, 0.3766]])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([2, 3])
tensor([2.5000, 0.1000])


In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
print("sum of x and y")
print(z)

# add function would not modify the host tensor, but the add_ function does
print(y.add_(x))
print(y)

tensor([[0.1445, 0.7154],
        [0.8088, 0.6621]])
tensor([[0.7645, 0.7664],
        [0.8327, 0.1506]])
sum of x and y
tensor([[0.9090, 1.4817],
        [1.6415, 0.8127]])
tensor([[0.9090, 1.4817],
        [1.6415, 0.8127]])
tensor([[0.9090, 1.4817],
        [1.6415, 0.8127]])


In [17]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x - y
print (x.sub(y))
# similarly, operations as mul and div can be 

tensor([[0.7259, 0.5034],
        [0.1668, 0.3339]])
tensor([[0.8962, 0.1619],
        [0.0563, 0.6240]])
tensor([[-0.1703,  0.3415],
        [ 0.1105, -0.2901]])


In [20]:
# slicing
x = torch.rand(5,3)
print(x)
print(x[1, :]) # second row and all the columns
print(x[1,1].item()) # get the actual values of 1 element tensor

tensor([[0.6058, 0.7305, 0.6586],
        [0.2745, 0.6927, 0.2562],
        [0.8198, 0.9753, 0.3856],
        [0.0570, 0.5409, 0.8849],
        [0.8872, 0.1441, 0.3155]])
tensor([0.2745, 0.6927, 0.2562])
0.6926777362823486


In [28]:
# reshaping tensor

x = torch.rand(4,4)
print(x)
y = x.view(16) # reshaping x from 4x4 matrix to 1D vector of 16 elements
print(y)
z = x.view(-1, 8) # put -1 if need to determine the dimension automatically. 
print(z)
print(z.size())

tensor([[0.6026, 0.1593, 0.9396, 0.9505],
        [0.5936, 0.7875, 0.4413, 0.0549],
        [0.6471, 0.1494, 0.5090, 0.1259],
        [0.5621, 0.4189, 0.7308, 0.5133]])
tensor([0.6026, 0.1593, 0.9396, 0.9505, 0.5936, 0.7875, 0.4413, 0.0549, 0.6471,
        0.1494, 0.5090, 0.1259, 0.5621, 0.4189, 0.7308, 0.5133])
tensor([[0.6026, 0.1593, 0.9396, 0.9505, 0.5936, 0.7875, 0.4413, 0.0549],
        [0.6471, 0.1494, 0.5090, 0.1259, 0.5621, 0.4189, 0.7308, 0.5133]])
torch.Size([2, 8])


In [40]:
import numpy as np

# convert a tensor to a np array
a = torch.ones(2,5)
print(a)
b = a.numpy()
print(b)
print(type(b))
#Caution: if the tensor is in CPU, the both object will share the same memory, 
# so changing one object will affect the other 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [45]:
import torch
import numpy as np

if torch.cuda.is_available(): # if there is a cuda device on the machine
    device = torch.device("cuda")
    print(torch.cuda.get_device_name()) # name of the GPU device
    x = torch.ones(5, device=device) # create a tensor on GPU
    y = torch.ones(5) # creates y on CPU
    y = y.to(device) # move Y to GPU
    z = x + y # compute Z on GPU
    print(z)
    #z.numpy() # this will return error cuz only tensors on CPU can be converted to numpy array
    z = z.to("cpu") # move z to CPU first
    print(z.numpy())
else: print("no cuda")

no cuda


In [42]:
x = torch.ones(5, requires_grad=True) # ask PyTorch to calculate the gradient later (optimized)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# autoGradient
Pytorch can store and track the function and automatically calculate the gradient for backpropagation if 

In [47]:
import torch
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2 # created a forward node (addition), 
#and a function is stored to calculate the gradient of y for backpropagation
print (y)

z = y*y*2
z = z.mean()
print(z)

# calculate the gradient, or the jacobian matrix of z in respect to x
z.backward() # dz/dx = J*x
print(x.grad)

tensor([-0.0157, -0.5796, -0.7077], requires_grad=True)
tensor([1.9843, 1.4204, 1.2923], grad_fn=<AddBackward0>)
tensor(5.0835, grad_fn=<MeanBackward0>)
tensor([2.6458, 1.8939, 1.7231])


In [49]:
#MAke sure that you are mindful about the dimensions matrix multiplication
# any matrix: n_rows x n_cols
# vector: n_rows x 1
# matrix multiplication: (n_rows1 x n_cols2) x (n_rows2 x n_col2) = (n_rows1 x n_col2)
# in this example: (3x3)(3x1) = (3x1)

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2 # created a forward node (addition), 
#and a function is stored to calculate the gradient of y for backpropagation
print (y)

z = y*y*2
#z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
# calculate the gradient, or the jacobian matrix of z in respect to x
z.backward(v) # dz/dx = J*v
print(x.grad)

tensor([-0.4329, -0.0458, -1.5283], requires_grad=True)
tensor([1.5671, 1.9542, 0.4717], grad_fn=<AddBackward0>)
tensor([4.9116, 7.6381, 0.4450], grad_fn=<MulBackward0>)
tensor([6.2684e-01, 7.8169e+00, 1.8867e-03])
